//AUTH
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'

//TIMETABLE
export const TIMETABLE_DATE = 'TIMETABLE_DATE'

//NAVBAR
export const NAVBAR_CHANGE_DD_VISIBILITY = 'NAVBAR_CHANGE_VISIBILITY'
export const NAVBAR_DD_REDIRECT = 'NAVBAR_DD_REDIRECT'
export const NAVBAR_HIDE_DD = 'NAVBAR_HIDE_DD'

//EDIT_PROFILE
export const LOAD_USERNAME_FROM_SERVER = 'LOAD_USERNAME_FROM_SERVER'
export const CHANGE_USER_NAME = 'CHANGE_USER_NAME'
export const CLEAR_USER_NAME = 'CLEAR_USER_NAME'

//USERS
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS'
export const FETCH_USERS_ERROR = 'FETCH_USERS_ERROR'
export const FETCH_USERS_START = 'FETCH_USERS_START'
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS'
export const FETCH_USER_ERROR = 'FETCH_USER_ERROR'
export const FETCH_USER_START = 'FETCH_USER_START'

//DIALOG
export const FETCH_MESSAGES_START = 'FETCH_MESSAGES_START'
export const FETCH_MESSAGES_SUCCESS = 'FETCH_MESSAGES_SUCCESS'
export const FETCH_MESSAGES_ERROR = 'FETCH_MESSAGES_ERROR'
export const SEND_MESSAGES_START = 'SEND_MESSAGES_START'
export const SEND_MESSAGES_SUCCESS = 'SEND_MESSAGES_SUCCESS'
export const SEND_MESSAGES_ERROR = 'SEND_MESSAGES_ERROR'
export const FETCH_USERS_DATA_START = 'FETCH_USERS_DATA_START'
export const FETCH_USERS_DATA_SUCCESS = 'FETCH_USERS_DATA_SUCCESS'

//DIALOGLIST
export const FETCH_DIALOGS_START = 'FETCH_DIALOGS_START'
export const FETCH_DIALOGS_SUCCESS = 'FETCH_DIALOGS_SUCCESS'
export const FETCH_DIALOGS_ERROR = 'FETCH_DIALOGS_ERROR'

//SIDEBAR
export const HOVER_SIDEBAR = 'HOVER_SIDEBAR'

export const CLEAR_STATE = 'CLEAR_STATE'
