//AUTH
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'
export const AUTH_ERROR = 'AUTH_ERROR'
export const LOGIN_ERROR = 'LOGIN_ERROR'

//TIMETABLE
export const TIMETABLE_DATE = 'TIMETABLE_DATE'

//EDIT_PROFILE
//export const LOAD_USERNAME_FROM_SERVER = 'LOAD_USERNAME_FROM_SERVER'
export const FETCH_USER_DATA_START = 'FETCH_USER_DATA_START'
export const FETCH_USER_DATA_SUCCESS = 'FETCH_USER_DATA_SUCCESS'
export const FETCH_USER_DATA_ERROR = 'FETCH_USER_DATA_ERROR'
export const SEND_USER_DATA_START = 'SEND_USER_DATA_START'
export const SEND_USER_DATA_SUCCESS_SHOW = 'SEND_USER_DATA_SUCCESS_SHOW'
export const SEND_USER_DATA_SUCCESS_HIDE = 'SEND_USER_DATA_SUCCESS_HIDE'

export const SEND_USER_DATA_ERROR = 'SEND_USER_DATA_ERROR'



//USERS
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS'
export const FETCH_USERS_ERROR = 'FETCH_USERS_ERROR'
export const FETCH_USERS_START = 'FETCH_USERS_START'
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS'
export const FETCH_USER_ERROR = 'FETCH_USER_ERROR'
export const FETCH_USER_START = 'FETCH_USER_START'

//DIALOG
export const FETCH_MESSAGES_START = 'FETCH_MESSAGES_START'
export const FETCH_MESSAGES_SUCCESS = 'FETCH_MESSAGES_SUCCESS'
export const FETCH_MESSAGES_ERROR = 'FETCH_MESSAGES_ERROR'
export const SEND_MESSAGES_START = 'SEND_MESSAGES_START'
export const SEND_MESSAGES_SUCCESS = 'SEND_MESSAGES_SUCCESS'
export const SEND_MESSAGES_ERROR = 'SEND_MESSAGES_ERROR'
export const FETCH_USERS_DATA_START = 'FETCH_USERS_DATA_START'
export const FETCH_USERS_DATA_SUCCESS = 'FETCH_USERS_DATA_SUCCESS'
export const SELECT_DIALOG = 'SELECT_DIALOG'
export const FETCH_DIALOG_INFO = 'FETCH_DIALOG_INFO'

//DIALOGLIST
export const FETCH_DIALOGS_START = 'FETCH_DIALOGS_START'
export const FETCH_DIALOGS_SUCCESS = 'FETCH_DIALOGS_SUCCESS'
export const FETCH_DIALOGS_ERROR = 'FETCH_DIALOGS_ERROR'

//SIDEBAR
export const HOVER_SIDEBAR = 'HOVER_SIDEBAR'

export const CLEAR_STATE = 'CLEAR_STATE'

export const TOGGLE_MODAL = 'TOGGLE_MODAL'


//CHANGES inside EDITPROFILE


//OPEN_USER
export const OPEN_USER = 'OPEN_USER'
export const CLOSE_USER = 'CLOSE_USER'

//TIMETABLE
export const FETCH_TIMETABLE_START = 'FETCH_TIMETABLE_START'
export const FETCH_TIMETABLE_SUCCESS = 'FETCH_TIMETABLE_SUCCESS'
export const FETCH_TIMETABLE_ERROR = 'FETCH_TIMETABLE_ERROR'
